from typing import Any, Dict, List, Text
from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
from rasa_sdk.events import SlotSet
import sqlite3


# -------------------------------------------------
# Helper: DB connection
# -------------------------------------------------
def get_db_connection():
    return sqlite3.connect("Food.db")


# -------------------------------------------------
# Add item to cart (DB-based)
# -------------------------------------------------
class ActionAddToCart(Action):

    def name(self) -> Text:
        return "action_add_to_cart"

    def run(
        self,
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: Dict[Text, Any]
    ) -> List[Dict[Text, Any]]:

        user_id = tracker.sender_id
        food = tracker.get_slot("food")
        quantity = tracker.get_slot("quantity")

        if not food:
            dispatcher.utter_message("❌ Please tell me which food item you want.")
            return []

        quantity = int(quantity) if quantity else 1
        food = food.lower()

        conn = get_db_connection()
        cursor = conn.cursor()

        # Get price from menu
        cursor.execute(
            "SELECT price FROM menu WHERE LOWER(name) = LOWER(?)",
            (food,)
        )
        result = cursor.fetchone()

        if not result:
            dispatcher.utter_message(f"❌ {food} is not available in our menu.")
            conn.close()
            return []

        price_per_item = result[0]
        total_price = price_per_item * quantity

        # Insert into cart
        cursor.execute(
            """
            INSERT INTO cart (user_id, food, quantity, price)
            VALUES (?, ?, ?, ?)
            """,
            (user_id, food, quantity, total_price)
        )

        conn.commit()
        conn.close()

        dispatcher.utter_message(
            f"✅ Added {quantity} {food}(s) to your cart (₹{total_price})"
        )

        return []


# -------------------------------------------------
# Show cart total
# -------------------------------------------------
class ActionShowTotal(Action):

    def name(self) -> Text:
        return "action_show_total"

    def run(
        self,
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: Dict[Text, Any]
    ) -> List[Dict[Text, Any]]:

        user_id = tracker.sender_id

        conn = get_db_connection()
        cursor = conn.cursor()

        cursor.execute(
            "SELECT food, quantity, price FROM cart WHERE user_id=?",
            (user_id,)
        )
        rows = cursor.fetchall()
        conn.close()

        if not rows:
            dispatcher.utter_message("🛒 Your cart is empty.")
            return []

        total = 0
        lines = []

        for food, qty, price in rows:
            total += price
            lines.append(f"{food} x {qty} = ₹{price}")

        dispatcher.utter_message(
            "🧾 Your cart:\n"
            + "\n".join(lines)
            + f"\n\n💰 Total: ₹{total}"
        )

        return []


# -------------------------------------------------
# Place order (order_id generated by DB)
# -------------------------------------------------
class ActionPlaceOrder(Action):

    def name(self) -> Text:
        return "action_place_order"

    def run(
        self,
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: Dict[Text, Any]
    ) -> List[Dict[Text, Any]]:

        user_id = tracker.sender_id
        payment_method = tracker.get_slot("payment_method") or "Cash on Delivery"

        conn = get_db_connection()
        cursor = conn.cursor()

        # Get cart items
        cursor.execute(
            "SELECT food, quantity, price FROM cart WHERE user_id=?",
            (user_id,)
        )
        cart_items = cursor.fetchall()

        if not cart_items:
            dispatcher.utter_message("❌ Your cart is empty.")
            conn.close()
            return []

        total_amount = sum(item[2] for item in cart_items)

        # Insert into orders (order_id auto-generated)
        cursor.execute(
            """
            INSERT INTO orders (user_id, total, payment_method, status)
            VALUES (?, ?, ?, ?)
            """,
            (user_id, total_amount, payment_method, "Placed")
        )

        order_id = cursor.lastrowid

        # Insert into order_items
        for food, qty, price in cart_items:
            cursor.execute(
                """
                INSERT INTO order_items (order_id, food, quantity, price)
                VALUES (?, ?, ?, ?)
                """,
                (order_id, food, qty, price)
            )

        # Clear cart
        cursor.execute(
            "DELETE FROM cart WHERE user_id=?",
            (user_id,)
        )

        conn.commit()
        conn.close()

        dispatcher.utter_message(
            f"🎉 Order placed successfully!\n"
            f"🆔 Order ID: {order_id}\n"
            f"💳 Payment: {payment_method}\n"
            f"📦 Status: Placed"
        )

        return [SlotSet("order_id", str(order_id))]


# -------------------------------------------------
# Track order status
# -------------------------------------------------
class ActionTrackOrder(Action):

    def name(self) -> Text:
        return "action_track_order"

    def run(
        self,
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: Dict[Text, Any]
    ) -> List[Dict[Text, Any]]:

        user_id = tracker.sender_id

        conn = get_db_connection()
        cursor = conn.cursor()

        cursor.execute(
            """
            SELECT order_id, status
            FROM orders
            WHERE user_id=?
            ORDER BY order_id DESC
            LIMIT 1
            """,
            (user_id,)
        )
        order = cursor.fetchone()
        conn.close()

        if not order:
            dispatcher.utter_message("❌ No active order found.")
            return []

        order_id, status = order

        dispatcher.utter_message(
            f"📦 Order ID: {order_id}\n"
            f"🚚 Current Status: {status}"
        )

        return []


# -------------------------------------------------
# Reorder last order
# -------------------------------------------------
class ActionReorderLast(Action):

    def name(self) -> Text:
        return "action_reorder_last"

    def run(
        self,
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: Dict[Text, Any]
    ) -> List[Dict[Text, Any]]:

        user_id = tracker.sender_id

        conn = get_db_connection()
        cursor = conn.cursor()

        # Get last order ID
        cursor.execute(
            """
            SELECT order_id
            FROM orders
            WHERE user_id=?
            ORDER BY order_id DESC
            LIMIT 1
            """,
            (user_id,)
        )
        row = cursor.fetchone()

        if not row:
            dispatcher.utter_message("⚠️ You don’t have any previous orders.")
            conn.close()
            return []

        last_order_id = row[0]

        # Get items from last order
        cursor.execute(
            """
            SELECT food, quantity, price
            FROM order_items
            WHERE order_id=?
            """,
            (last_order_id,)
        )
        items = cursor.fetchall()

        # Insert items back into cart
        for food, qty, price in items:
            cursor.execute(
                """
                INSERT INTO cart (user_id, food, quantity, price)
                VALUES (?, ?, ?, ?)
                """,
                (user_id, food, qty, price)
            )

        conn.commit()
        conn.close()

        dispatcher.utter_message(
            "🔁 Items from your last order have been added to your cart."
        )

        return []
